# Generated by Django 5.1.1 on 2024-09-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Введите фото', upload_to='uploads/images', verbose_name='Обложка')),
                ('name', models.CharField(help_text='Введите название книги', max_length=100, verbose_name='Название книги')),
                ('description', models.TextField(help_text='Введите описание книги', verbose_name='Описание книги')),
                ('genre', models.CharField(help_text='Введите жанр книги', max_length=100, verbose_name='Жанр книги')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену книги', max_digits=10, verbose_name='Цена книги')),
                ('author', models.CharField(help_text='Введите автора книги', max_length=100, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
